volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
                    device: /home/ael-amin/data/wordpress
                    o: bind
                    type: none
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
               device: /home/ael-amin/data/mariadb
               o: bind
               type: none


networks:
    inception:
        driver: bridge

services:
      nginx:
        image: nginx:ng
        container_name: nginx
        build: ./requirements/nginx/.
        ports:
          - 443:443
        depends_on:
          - wordpress
        volumes:
         - wordpress:/var/www/html
        networks:
          - inception
        restart: always
      wordpress:
        image: wordpress:wp
        container_name: wordpress
        build: ./requirements/wordpress/.
        depends_on:
          - mariadb
        volumes:
          - wordpress:/var/www/html
        env_file:
          - .env
        networks:
          - inception
        restart: always
      mariadb:
        image: mariadb:db
        container_name: mariadb
        build: ./requirements/mariadb/.
        volumes:
          - mariadb:/var/lib/mysql
        env_file:
          - .env
        networks:
          - inception
        restart: always


